### ISSUE TITLE
BUG: busybox image not found

### ISSUE THREAD

**Issue by dionjwa** [Autodesk/cloud-compute-cannon#64]
When running tests on the demo server, it complains that the busybox image isn't found, even though there is a specific check for images, and it should fail that check, but instead its attempting to create a container with the image apparently not there:

```
Error: (HTTP code 404) no such container - No such image: busybox:latest

    at /app/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/app/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:259:7)
    at [object Object].Modem.buildPayload (/app/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/app/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

```

**Comment by dionjwa** [comment]
This was fixed quite a while ago, including a functional test with a bogus docker image.
